# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-30 12:25
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('adress', models.TextField(max_length=100)),
                ('profilePic', models.ImageField(upload_to='images/%Y%m%d/')),
                ('contact', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must have 12 digits including country code', regex='^?\\+\\d{10,12})')])),
                ('gender', models.CharField(max_length=1)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
