# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-30 12:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180630_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must have 12 digits including country code', regex='^\\+{0,1}\\d{10,12}')]),
        ),
    ]
